authors = ["DiscordLuau"]
description = "A Discord API wrapper, written in luau!"
entrypoint = "./Package/init.luau"
include = ["Package", "lpm-package.toml"]
licence = "None"
name = "discord-luau"
repository = "https://github.com/4x8Matrix/Pengu-Bot"
version = "0.1.0"

[dependencies]

[scripts]
